import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import solc from 'solc';
import { ethers } from 'ethers';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
    console.log("Compiling ArcherPool.sol...");
    
    // 1. Read the Solidity source
    const contractPath = path.resolve(__dirname, '../contracts/Archer.sol');
    const source = fs.readFileSync(contractPath, 'utf8');

    // 2. Format compiler input
    const input = {
        language: 'Solidity',
        sources: {
            'Archer.sol': {
                content: source,
            },
        },
        settings: {
            outputSelection: {
                '*': {
                    '*': ['*'],
                },
            },
        },
    };

    // 3. Compile
    const compiled = JSON.parse(solc.compile(JSON.stringify(input)));
    
    if (compiled.errors) {
        let hasErrors = false;
        for (const err of compiled.errors) {
            console.error(err.formattedMessage);
            if (err.severity === 'error') hasErrors = true;
        }
        if (hasErrors) {
            console.log("Compilation failed.");
            process.exit(1);
        }
    }

    const contractFile = compiled.contracts['Archer.sol']['ArcherPool'];
    const abi = contractFile.abi;
    const bytecode = contractFile.evm.bytecode.object;

    console.log("Compilation successful!");
    
    // 4. Set up Ethers to Arc Testnet
    const RPC_URL = "https://rpc.testnet.arc.network";
    const provider = new ethers.JsonRpcProvider(RPC_URL);
    
    // The private key we generated locally
    const PRIVATE_KEY = "0xeb4dbc4b8bbdd24530df3f7fa2239f0a3d3fdf062e88d6af4c94593dff138d66";
    const wallet = new ethers.Wallet(PRIVATE_KEY, provider);

    console.log(`\nDeploying from address: ${wallet.address}`);
    
    // Check balance first
    const balance = await provider.getBalance(wallet.address);
    console.log(`Current Balance: ${ethers.formatUnits(balance, 18)} USDC`);

    // Arc gas token is USDC. If balance is 0, we can't deploy.
    if (balance === 0n) {
        console.error("\n❌ ERROR: Deployer wallet has 0 balance.");
        console.error("Please fund this address with Testnet USDC before deploying:");
        console.error(`--> ${wallet.address}`);
        process.exit(1);
    }

    // 5. Deploy
    console.log("\nBroadcasting deployment transaction...");
    const factory = new ethers.ContractFactory(abi, bytecode, wallet);
    const contract = await factory.deploy();
    
    console.log("Waiting for block confirmation...");
    await contract.waitForDeployment();
    
    const deployedAddress = await contract.getAddress();
    console.log(`\n✅ Contract deployed successfully to: ${deployedAddress}`);

    // 6. Automatically generate the frontend integration file
    console.log("Generating frontend ABI wrapper...");
    const wrapperContent = `// Auto-generated by deploy script
import { Interface } from 'ethers';

export const CONTRACT_ADDRESS = "${deployedAddress}";

export const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)};

export const contractInterface = new Interface(CONTRACT_ABI);
`;

    const wrapperDir = path.resolve(__dirname, '../src/lib');
    if (!fs.existsSync(wrapperDir)) fs.mkdirSync(wrapperDir, { recursive: true });
    
    fs.writeFileSync(path.resolve(wrapperDir, 'contract.ts'), wrapperContent, 'utf8');
    
    console.log(`Frontend updated: src/lib/contract.ts created.`);
}

main().catch(console.error);
